config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subjects do
    member do
      put 'like', to: 'subjects#upvote'
    end
  end

  root 'subjects#index'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  acts_as_votable
  belongs_to  :user

  def last_name
    self.name.split(' ')[1]
  end
  
  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @subjects = Subject.all.sort { |a, b| a.last_name <=> b.last_name }
  end

  def show
  end

  def new
    @subject = current_user.subjects.build
  end

  def create
    @subject = current_user.subjects.build(subject_params)

    if @subject.save
      redirect_to @subject, notice: "Successfully added Individual"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: "Individual was Successfully Updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @subject.destroy
    redirect_to root_path
  end

  def upvote
    @subject.upvote_by current_user
    redirect_to :back
  end

  private
    def find_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title CodeEquality
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to 'CodeEquality', root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Individual", new_subject_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: 'alert alert-info'

    = yield

app/views/subjects/_form.html.haml
= simple_form_for @subject, html: { multipart: true } do |f|
  - if @subject.errors.any?
    #errors
      %h2
      = pluralize(@subject.errors.count, "error")
      prevented this individual from saving
      %ul
        - @subject.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :name, input_html: { class: 'form-control' }

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  = f.button :submit, class: 'btn btn-primary'

app/views/subjects/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Individual
      .panel-body
        %strong.center Current Image
        %br/
        = image_tag @subject.image.url(:medium)
        %br/
        = render 'form'

app/views/subjects/index.html.haml
#subjects.transitions-enabled
  - @subjects.each do |subject|
    .box.panel.panel-default
      = link_to (image_tag subject.image.url), subject
      .panel-body
        %h2= link_to subject.name, subject

app/views/subjects/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Add Individual by Name
      .panel-body
        = render 'form'

app/views/subjects/show.html.haml
#subject_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.subject_image
        = image_tag @subject.image.url
      .panel-body
        %h1= @subject.name
        %p.bio= @subject.bio
      .panel-footer
        .row
          .col-md-6
            %p
          .col-md-6
            .btn-group.pull-right
              = link_to like_subject_path(@subject), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                  = @subject.get_upvotes.size
              - if user_signed_in?
                = link_to 'Edit', edit_subject_path, class: "btn btn-default"
                / = link_to 'Delete', subject_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"